# Dockerfile for echoServer, e.g. CMD v.s. RUN  example

FROM centos:latest
MAINTAINER e.e.cornet@gmail.com

RUN useradd -ms /bin/bash user


ENTRYPOINT echo "This command will display this message on EVERY container"
